import type { INodeProperties } from 'n8n-workflow';

const extendedEventFields: INodeProperties[] = [
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		default: '',
		placeholder: 'https://example.com/meeting',
		description: 'Canonical URL associated with the event',
	},
	{
		displayName: 'Status',
		name: 'status',
		type: 'options',
		default: 'CONFIRMED',
		options: [
			{ name: 'Cancelled', value: 'CANCELLED' },
			{ name: 'Confirmed', value: 'CONFIRMED' },
			{ name: 'Tentative', value: 'TENTATIVE' },
		],
		description: 'Overall status of the event',
	},
	{
		displayName: 'Availability',
		name: 'availability',
		type: 'options',
		default: 'busy',
		options: [
			{ name: 'Busy', value: 'busy' },
			{ name: 'Free', value: 'free' },
		],
		description: 'Whether the event blocks time in the calendar',
	},
	{
		displayName: 'Classification',
		name: 'classification',
		type: 'options',
		default: 'PUBLIC',
		options: [
			{ name: 'Confidential', value: 'CONFIDENTIAL' },
			{ name: 'Private', value: 'PRIVATE' },
			{ name: 'Public', value: 'PUBLIC' },
		],
		description: 'Access classification of the event',
	},
	{
		displayName: 'Priority',
		name: 'priority',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0, maxValue: 9 },
		description: 'iCalendar priority from 0 (undefined) to 9 (lowest), with 1 being highest',
	},
	{
		displayName: 'Sequence',
		name: 'sequence',
		type: 'number',
		default: 0,
		typeOptions: { minValue: 0 },
		description: 'Revision number. Updates increment the existing value automatically when omitted.',
	},
	{
		displayName: 'Organizer (JSON)',
		name: 'organizer',
		type: 'json',
		default: '',
		placeholder: '{"name":"Alex","email":"alex@example.com","uri":"mailto:alex@example.com"}',
		description: 'Organizer object. Supports uri, email, name, sentBy, directory, and language.',
	},
	{
		displayName: 'Attendees (JSON)',
		name: 'attendees',
		type: 'json',
		default: '',
		placeholder: '[{"name":"Sam","email":"sam@example.com","uri":"mailto:sam@example.com","role":"REQ-PARTICIPANT","rsvp":true}]',
		description: 'Array of attendees, including role, participationStatus, RSVP, delegation, and user type',
	},
	{
		displayName: 'Recurrence Rules (JSON)',
		name: 'recurrenceRules',
		type: 'json',
		default: '',
		placeholder: '["FREQ=DAILY;COUNT=4"]',
		description: 'Array of RFC 5545 RRULE values without the RRULE prefix',
	},
	{
		displayName: 'Recurrence Dates (JSON)',
		name: 'recurrenceDates',
		type: 'json',
		default: '',
		placeholder: '["2026-08-24T08:00:00"]',
		description: 'Array of additional recurrence dates (RDATE)',
	},
	{
		displayName: 'Excluded Dates (JSON)',
		name: 'excludedDates',
		type: 'json',
		default: '',
		placeholder: '["2026-08-23T08:00:00"]',
		description: 'Array of excluded recurrence dates (EXDATE)',
	},
	{
		displayName: 'Categories (JSON)',
		name: 'categories',
		type: 'json',
		default: '',
		placeholder: '["Work","Meeting"]',
		description: 'Array of event categories',
	},
	{
		displayName: 'Geo Position (JSON)',
		name: 'geo',
		type: 'json',
		default: '',
		placeholder: '{"latitude":52.52,"longitude":13.405}',
		description: 'Geographic position with latitude and longitude',
	},
	{
		displayName: 'Attachments (JSON)',
		name: 'attachments',
		type: 'json',
		default: '',
		placeholder: '[{"value":"https://example.com/file.pdf","formatType":"application/pdf","valueType":"URI"}]',
		description: 'Array of attachments with value and optional formatType, encoding, and valueType',
	},
	{
		displayName: 'Alarms (JSON)',
		name: 'alarms',
		type: 'json',
		default: '',
		placeholder: '[{"name":"VALARM","properties":[{"name":"ACTION","value":"DISPLAY","rawValue":"DISPLAY","parameters":{}},{"name":"TRIGGER","value":"-PT15M","rawValue":"-PT15M","parameters":{}}],"components":[]}]',
		description: 'Array of complete VALARM components',
	},
	{
		displayName: 'Comments (JSON)',
		name: 'comments',
		type: 'json',
		default: '',
		placeholder: '["Bring the latest report"]',
		description: 'Array of iCalendar COMMENT values',
	},
	{
		displayName: 'Contacts (JSON)',
		name: 'contacts',
		type: 'json',
		default: '',
		placeholder: '["Project office"]',
		description: 'Array of contact references associated with the event',
	},
	{
		displayName: 'Resources (JSON)',
		name: 'resources',
		type: 'json',
		default: '',
		placeholder: '["Projector","Room 4"]',
		description: 'Array of resources reserved by the event',
	},
	{
		displayName: 'Related-To Properties (JSON)',
		name: 'relatedTo',
		type: 'json',
		default: '',
		placeholder: '[{"name":"RELATED-TO","value":"parent-uid","rawValue":"parent-uid","parameters":{"RELTYPE":["PARENT"]}}]',
		description: 'Array of complete RELATED-TO properties',
	},
	{
		displayName: 'Request Status Values (JSON)',
		name: 'requestStatus',
		type: 'json',
		default: '',
		placeholder: '["2.0;Success"]',
		description: 'Array of REQUEST-STATUS values',
	},
	{
		displayName: 'Custom Properties (JSON)',
		name: 'customProperties',
		type: 'json',
		default: '',
		placeholder: '[{"name":"X-APPLE-TRAVEL-DURATION","value":"PT30M","rawValue":"PT30M","parameters":{}}]',
		description: 'Arbitrary iCalendar properties. Existing properties with the same name are replaced on update.',
	},
	{
		displayName: 'Custom Components (JSON)',
		name: 'customComponents',
		type: 'json',
		default: '',
		placeholder: '[{"name":"X-COMPONENT","properties":[],"components":[]}]',
		description: 'Arbitrary nested iCalendar components. Existing components with the same name are replaced on update.',
	},
];

export const calendarOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['calendar'],
			},
		},
		options: [
			{
				name: 'Get Calendars',
				value: 'getCalendars',
				description: 'List all calendars in iCloud',
				action: 'List all iCloud calendars',
			},
			{
				name: 'Get Events',
				value: 'getEvents',
				description: 'Retrieve calendar events within a date range',
				action: 'Get calendar events from iCloud',
			},
			{
				name: 'Create Event',
				value: 'createEvent',
				description: 'Create a new calendar event in iCloud',
				action: 'Create a calendar event in iCloud',
			},
			{
				name: 'Update Event',
				value: 'updateEvent',
				description: 'Update an existing calendar event',
				action: 'Update a calendar event in iCloud',
			},
			{
				name: 'Delete Event',
				value: 'deleteEvent',
				description: 'Delete a calendar event from iCloud',
				action: 'Delete a calendar event from iCloud',
			},
		],
		default: 'getEvents',
	},
];

export const calendarFields: INodeProperties[] = [
	// ─── Get Events ───────────────────────────────────────────────────────────────
	{
		displayName: 'Calendar',
		name: 'calendarUrl',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getCalendarOptionsWithAll',
		},
		displayOptions: {
			show: { resource: ['calendar'], operation: ['getEvents'] },
		},
		default: '',
		description: 'Calendar to fetch events from. Select "All Calendars" to fetch from all.',
	},
	{
		displayName: 'Start Date',
		name: 'start',
		type: 'dateTime',
		displayOptions: {
			show: { resource: ['calendar'], operation: ['getEvents'] },
		},
		default: '',
		description: 'Start of the date range to fetch events for',
	},
	{
		displayName: 'End Date',
		name: 'end',
		type: 'dateTime',
		displayOptions: {
			show: { resource: ['calendar'], operation: ['getEvents'] },
		},
		default: '',
		description: 'End of the date range to fetch events for',
	},
	{
		displayName: 'Include Raw iCalendar Data',
		name: 'includeRawData',
		type: 'boolean',
		displayOptions: {
			show: { resource: ['calendar'], operation: ['getEvents'] },
		},
		default: false,
		description: 'Whether to include every raw property, nested component, DAV URL, ETag, and the complete ICS document. This can make each event several kilobytes larger.',
	},

	// ─── Create Event ─────────────────────────────────────────────────────────────
	{
		displayName: 'Calendar',
		name: 'calendarUrl',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getCalendarOptions',
		},
		required: true,
		displayOptions: {
			show: { resource: ['calendar'], operation: ['createEvent'] },
		},
		default: '',
		description: 'Calendar to create the event in',
	},
	{
		displayName: 'Summary (Title)',
		name: 'summary',
		type: 'string',
		required: true,
		displayOptions: {
			show: { resource: ['calendar'], operation: ['createEvent'] },
		},
		default: '',
		placeholder: 'Meeting with team',
		description: 'Title/summary of the calendar event',
	},
	{
		displayName: 'Start',
		name: 'start',
		type: 'dateTime',
		required: true,
		displayOptions: {
			show: { resource: ['calendar'], operation: ['createEvent'] },
		},
		default: '',
		placeholder: '2026-03-06T15:00:00Z',
		description:
			'Start date and time. Without a Timezone field, this must be UTC (use Z suffix, e.g. 2026-03-06T15:00:00Z). For local wall-clock time, set the Timezone field.',
	},
	{
		displayName: 'End',
		name: 'end',
		type: 'dateTime',
		required: true,
		displayOptions: {
			show: { resource: ['calendar'], operation: ['createEvent'] },
		},
		default: '',
		placeholder: '2026-03-06T16:00:00Z',
		description:
			'End date and time. Without a Timezone field, this must be UTC (use Z suffix, e.g. 2026-03-06T16:00:00Z). For local wall-clock time, set the Timezone field.',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['calendar'], operation: ['createEvent'] },
		},
		options: [
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				typeOptions: { rows: 3 },
				description: 'Detailed description or notes for the event',
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'Conference Room A',
				description: 'Location where the event takes place',
			},
			{
				displayName: 'All Day Event',
				name: 'allDay',
				type: 'boolean',
				default: false,
				description: 'Whether this is an all-day event (ignores time portion)',
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getTimezones' },
				default: '',
				description: 'IANA timezone for the event. Leave empty to use UTC.',
			},
			...extendedEventFields,
		],
	},

	// ─── Update / Delete Event ────────────────────────────────────────────────────
	{
		displayName: 'Calendar',
		name: 'calendarUrl',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getCalendarOptions',
		},
		required: true,
		displayOptions: {
			show: { resource: ['calendar'], operation: ['updateEvent', 'deleteEvent'] },
		},
		default: '',
		description: 'Calendar that contains the event',
	},
	{
		displayName: 'Event UID',
		name: 'uid',
		type: 'string',
		required: true,
		displayOptions: {
			show: { resource: ['calendar'], operation: ['updateEvent', 'deleteEvent'] },
		},
		default: '',
		placeholder: 'lm3abc12-def4-...',
		description: 'UID of the event to update or delete. Returned as the "uid" field by "Get Events" or "Create Event".',
	},
	{
		displayName: 'Fields to Update',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: { resource: ['calendar'], operation: ['updateEvent'] },
		},
		options: [
			{
				displayName: 'Summary (Title)',
				name: 'summary',
				type: 'string',
				default: '',
				description: 'New title for the event',
			},
			{
				displayName: 'Start',
				name: 'start',
				type: 'dateTime',
				default: '',
				description: 'New start date/time for the event',
			},
			{
				displayName: 'End',
				name: 'end',
				type: 'dateTime',
				default: '',
				description: 'New end date/time for the event',
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				typeOptions: { rows: 3 },
				description: 'New description for the event',
			},
			{
				displayName: 'Location',
				name: 'location',
				type: 'string',
				default: '',
				description: 'New location for the event',
			},
			{
				displayName: 'All Day Event',
				name: 'allDay',
				type: 'boolean',
				default: false,
				description: 'Whether to make this an all-day event',
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'options',
				typeOptions: { loadOptionsMethod: 'getTimezones' },
				default: '',
				description: 'IANA timezone for the event. Leave empty to keep existing timezone.',
			},
			...extendedEventFields,
		],
	},
];
